name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libtool \
          autoconf
        pip install buildozer setuptools
        
    - name: Build APK
      run: |
        buildozer init
        cp buildozer.spec buildozer.spec.bak
        curl -O https://gist.githubusercontent.com/mahmudkz/.../raw/buildozer.spec
        buildozer -v android debug
