name: All Builds (APK)

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - master
      - main
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git zip unzip openjdk-17-jdk
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize Buildozer
      run: |
        buildozer init
        # Edit buildozer.spec if needed
        # For example, set the app title, package name, etc.
        sed -i 's/^title = .*/title = MyApp/' buildozer.spec
        sed -i 's/^package.name = .*/package.name = myapp/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.test/' buildozer.spec

    - name: Build Android APK
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: android-build-artifact
        path: bin
        if-no-files-found: warn
        overwrite: false
