name: Universal APK Builder

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.12.2"
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          libgl1-mesa-glx \
          libglu1-mesa \
          libsm6 \
          libxi6 \
          libxrender1 \
          libxkbcommon-x11-0 \
          libgtk-3-0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android tools
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 26.1.10909125
        build-tools-version: 34.0.0
        platform-version: 34
        cmake-version: 3.22.1
        accept-android-licenses: true

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython setuptools==69.0.3
        pip install -r requirements.txt

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
        retention-days: 7

    - name: Store build logs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: build-logs
        path: |
          buildozer.spec
          .buildozer/**/*.log
