name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libtool \
          autoconf
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer kivy plyer
        
    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i "s/^requirements = .*/requirements = python3,kivy,plyer/" buildozer.spec
        sed -i "s/^android.sdk_version = .*/android.sdk_version = 34/" buildozer.spec
        sed -i "s/^android.ndk = .*/android.ndk = 26.1.10909125/" buildozer.spec
        
    - name: Accept licenses
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
