name: Android Build

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: "1.0.0"
  PYTHON_VERSION: "3.12"
  ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
  ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libtool \
            autoconf \
            libssl-dev \
            python3-venv

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools buildozer cython

      - name: Initialize Buildozer
        run: |
          buildozer init
          sed -i "s/^requirements = .*/requirements = python3,kivy,plyer/" buildozer.spec
          sed -i "s/^android.ndk = .*/android.ndk = 26.1.10909125/" buildozer.spec
          sed -i "s/^android.sdk_version = .*/android.sdk_version = 34/" buildozer.spec

      - name: Accept licenses and install tools
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools"

      - name: Build APK
        run: |
          buildozer -v android debug
