name: All Builds (APK)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git zip unzip openjdk-17-jdk libtool autoconf
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Navigate to project directory
      run: |
        cd path/to/your/project

    - name: Update configure.ac
      run: |
        autoupdate

    - name: Run autoreconf
      run: |
        autoreconf -fvi

    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/^title = .*/title = MyApp/' buildozer.spec
        sed -i 's/^package.name = .*/package.name = myapp/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.test/' buildozer.spec
        sed -i 's/^requirements = .*/requirements = python3,kivy,plyer/' buildozer.spec

    - name: Build Android APK
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: android-build-artifact
        path: bin
        if-no-files-found: warn
        overwrite: false
