name: All Builds (APK)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.10  # استخدم إصدار متوافق مع Kivy
  FLUTTER_VERSION: 3.22.2

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Patch for linux build
      run: |
        flutter doctor
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        flutter doctor

    - name: Flet Build Linux
      run: |
        flutter config --no-analytics 
        flet build linux --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-artifact
        path: build/linux
        if-no-files-found: warn
        overwrite: false

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  build-android:
    runs-on: ubuntu-latest  # Buildozer يعمل بشكل أفضل على لينكس

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python for Buildozer
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"  # متوافق مع Buildozer و Kivy

    - name: Install Buildozer & Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git zip unzip openjdk-17-jdk
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk  # تأكد من أن هذا المسار يتوافق مع مخرجات Buildozer
        if-no-files-found: warn
        overwrite: false
