name: All Builds (APK)

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
  ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize Buildozer
        run: |
          buildozer init
          buildozer -v android debug  # Initializes SDK first

      - name: Accept licenses
        run: |
          yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Build-Tools
        run: |
          $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      - name: Build APK
        run: |
          buildozer -v android debug
